/* The following code was generated by JFlex 1.6.1 */

/*-***
 *
 * This file defines a stand-alone lexical analyzer for a song-file which is
 * written in chordpro or onsong format.
 *
 * Created with <TT>java -jar jflex-1.6.1.jar SongParserLogic.jflex</TT>
 *
 */

package org.openskies.songbook.printer.parser;

import java.util.ArrayList;
import java.util.List;

import org.openskies.songbook.printer.elements.ChordElement;
import org.openskies.songbook.printer.elements.ChordproElement;
import org.openskies.songbook.printer.elements.FakebreakElement;
import org.openskies.songbook.printer.elements.LinebreakElement;
import org.openskies.songbook.printer.elements.OnsongElement;
import org.openskies.songbook.printer.elements.SongElement;
import org.openskies.songbook.printer.elements.SongElementType;
import org.openskies.songbook.printer.elements.WordElement;
import java.util.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>SongParserLogic.jflex</tt>
 */
class LexicalSongParser {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\15\1\7\1\6\1\6\1\10\22\0\1\15\14\1\1\13"+
    "\2\1\12\12\1\14\6\1\32\12\1\2\1\0\1\3\1\0\1\11"+
    "\1\0\32\12\1\4\1\0\1\5\7\0\1\6\33\0\11\1\1\12"+
    "\12\1\1\12\4\1\1\12\5\1\27\12\1\1\37\12\1\1\10\12"+
    "\u01c2\11\4\0\14\11\16\0\5\11\7\0\1\11\1\0\1\11\21\0"+
    "\165\11\1\0\2\11\2\0\4\11\1\0\1\11\6\0\1\11\1\0"+
    "\3\11\1\0\1\11\1\0\24\11\1\0\123\11\1\0\213\11\1\0"+
    "\255\11\1\0\46\11\2\0\1\11\7\0\47\11\11\0\55\11\1\0"+
    "\1\11\1\0\2\11\1\0\2\11\1\0\1\11\10\0\33\11\5\0"+
    "\3\11\35\0\13\11\5\0\112\11\4\0\146\11\1\0\10\11\2\0"+
    "\12\11\1\0\23\11\2\0\1\11\20\0\73\11\2\0\145\11\16\0"+
    "\66\11\4\0\1\11\5\0\56\11\22\0\34\11\104\0\23\11\61\0"+
    "\200\11\2\0\12\11\1\0\23\11\1\0\10\11\2\0\2\11\2\0"+
    "\26\11\1\0\7\11\1\0\1\11\3\0\4\11\2\0\11\11\2\0"+
    "\2\11\2\0\4\11\10\0\1\11\4\0\2\11\1\0\5\11\2\0"+
    "\14\11\17\0\3\11\1\0\6\11\4\0\2\11\2\0\26\11\1\0"+
    "\7\11\1\0\2\11\1\0\2\11\1\0\2\11\2\0\1\11\1\0"+
    "\5\11\4\0\2\11\2\0\3\11\3\0\1\11\7\0\4\11\1\0"+
    "\1\11\7\0\20\11\13\0\3\11\1\0\11\11\1\0\3\11\1\0"+
    "\26\11\1\0\7\11\1\0\2\11\1\0\5\11\2\0\12\11\1\0"+
    "\3\11\1\0\3\11\2\0\1\11\17\0\4\11\2\0\12\11\21\0"+
    "\3\11\1\0\10\11\2\0\2\11\2\0\26\11\1\0\7\11\1\0"+
    "\2\11\1\0\5\11\2\0\11\11\2\0\2\11\2\0\3\11\10\0"+
    "\2\11\4\0\2\11\1\0\5\11\2\0\12\11\1\0\1\11\20\0"+
    "\2\11\1\0\6\11\3\0\3\11\1\0\4\11\3\0\2\11\1\0"+
    "\1\11\1\0\2\11\3\0\2\11\3\0\3\11\3\0\14\11\4\0"+
    "\5\11\3\0\3\11\1\0\4\11\2\0\1\11\6\0\1\11\16\0"+
    "\12\11\20\0\4\11\1\0\10\11\1\0\3\11\1\0\27\11\1\0"+
    "\20\11\3\0\10\11\1\0\3\11\1\0\4\11\7\0\2\11\1\0"+
    "\2\11\6\0\4\11\2\0\12\11\21\0\3\11\1\0\10\11\1\0"+
    "\3\11\1\0\27\11\1\0\12\11\1\0\5\11\2\0\11\11\1\0"+
    "\3\11\1\0\4\11\7\0\2\11\7\0\1\11\1\0\4\11\2\0"+
    "\12\11\1\0\2\11\16\0\3\11\1\0\10\11\1\0\3\11\1\0"+
    "\51\11\2\0\10\11\1\0\3\11\1\0\5\11\10\0\1\11\10\0"+
    "\4\11\2\0\12\11\12\0\6\11\2\0\2\11\1\0\22\11\3\0"+
    "\30\11\1\0\11\11\1\0\1\11\2\0\7\11\3\0\1\11\4\0"+
    "\6\11\1\0\1\11\1\0\10\11\6\0\12\11\2\0\2\11\15\0"+
    "\72\11\5\0\17\11\1\0\12\11\47\0\2\11\1\0\1\11\2\0"+
    "\2\11\1\0\1\11\2\0\1\11\6\0\4\11\1\0\7\11\1\0"+
    "\3\11\1\0\1\11\1\0\1\11\2\0\2\11\1\0\15\11\1\0"+
    "\3\11\2\0\5\11\1\0\1\11\1\0\6\11\2\0\12\11\2\0"+
    "\4\11\40\0\1\11\27\0\2\11\6\0\12\11\13\0\1\11\1\0"+
    "\1\11\1\0\1\11\4\0\12\11\1\0\44\11\4\0\24\11\1\0"+
    "\22\11\1\0\44\11\11\0\1\11\71\0\112\11\6\0\116\11\2\0"+
    "\46\11\1\0\1\11\5\0\1\11\2\0\53\11\1\0\u014d\11\1\0"+
    "\4\11\2\0\7\11\1\0\1\11\1\0\4\11\2\0\51\11\1\0"+
    "\4\11\2\0\41\11\1\0\4\11\2\0\7\11\1\0\1\11\1\0"+
    "\4\11\2\0\17\11\1\0\71\11\1\0\4\11\2\0\103\11\2\0"+
    "\3\11\40\0\20\11\20\0\125\11\14\0\u026c\11\2\0\21\11\1\0"+
    "\32\11\5\0\113\11\3\0\13\11\7\0\15\11\1\0\7\11\13\0"+
    "\25\11\13\0\24\11\14\0\15\11\1\0\3\11\1\0\2\11\14\0"+
    "\124\11\3\0\1\11\4\0\2\11\2\0\12\11\41\0\3\11\2\0"+
    "\12\11\6\0\130\11\10\0\53\11\5\0\106\11\12\0\37\11\1\0"+
    "\14\11\4\0\14\11\12\0\50\11\2\0\5\11\13\0\54\11\4\0"+
    "\32\11\6\0\12\11\46\0\34\11\4\0\77\11\1\0\35\11\2\0"+
    "\13\11\6\0\12\11\15\0\1\11\10\0\17\11\101\0\114\11\4\0"+
    "\12\11\21\0\11\11\14\0\164\11\14\0\70\11\10\0\12\11\3\0"+
    "\61\11\122\0\3\11\1\0\43\11\1\0\2\11\6\0\366\11\6\0"+
    "\u011a\11\2\0\6\11\2\0\46\11\2\0\6\11\2\0\10\11\1\0"+
    "\1\11\1\0\1\11\1\0\1\11\1\0\37\11\2\0\65\11\1\0"+
    "\7\11\1\0\1\11\3\0\3\11\1\0\7\11\3\0\4\11\2\0"+
    "\6\11\4\0\15\11\5\0\3\11\1\0\7\11\53\0\1\6\1\6"+
    "\25\0\2\11\23\0\1\11\34\0\1\11\15\0\1\11\20\0\15\11"+
    "\63\0\41\11\21\0\1\11\4\0\1\11\2\0\12\11\1\0\1\11"+
    "\3\0\5\11\6\0\1\11\1\0\1\11\1\0\1\11\1\0\4\11"+
    "\1\0\13\11\2\0\4\11\5\0\5\11\4\0\1\11\21\0\51\11"+
    "\u032d\0\64\11\u0716\0\57\11\1\0\57\11\1\0\205\11\6\0\11\11"+
    "\14\0\46\11\1\0\1\11\5\0\1\11\2\0\70\11\7\0\1\11"+
    "\17\0\30\11\11\0\7\11\1\0\7\11\1\0\7\11\1\0\7\11"+
    "\1\0\7\11\1\0\7\11\1\0\7\11\1\0\7\11\1\0\40\11"+
    "\57\0\1\11\u01d5\0\3\11\31\0\17\11\1\0\5\11\2\0\5\11"+
    "\4\0\126\11\2\0\2\11\2\0\3\11\1\0\132\11\1\0\4\11"+
    "\5\0\51\11\3\0\136\11\21\0\33\11\65\0\20\11\u0200\0\u19b6\11"+
    "\112\0\u51cd\11\63\0\u048d\11\103\0\56\11\2\0\u010d\11\3\0\34\11"+
    "\24\0\63\11\1\0\12\11\1\0\37\11\1\0\123\11\45\0\11\11"+
    "\2\0\147\11\2\0\4\11\1\0\36\11\2\0\2\11\105\0\61\11"+
    "\30\0\64\11\14\0\105\11\13\0\12\11\6\0\30\11\3\0\1\11"+
    "\4\0\56\11\2\0\44\11\14\0\35\11\3\0\101\11\16\0\13\11"+
    "\6\0\37\11\1\0\67\11\11\0\16\11\2\0\12\11\6\0\27\11"+
    "\3\0\111\11\30\0\3\11\2\0\20\11\2\0\5\11\12\0\6\11"+
    "\2\0\6\11\2\0\6\11\11\0\7\11\1\0\7\11\1\0\53\11"+
    "\1\0\4\11\4\0\2\11\132\0\53\11\1\0\2\11\2\0\12\11"+
    "\6\0\u2ba4\11\14\0\27\11\4\0\61\11\u2104\0\u016e\11\2\0\152\11"+
    "\46\0\7\11\14\0\5\11\5\0\14\11\1\0\15\11\1\0\5\11"+
    "\1\0\1\11\1\0\2\11\1\0\2\11\1\0\154\11\41\0\u016b\11"+
    "\22\0\100\11\2\0\66\11\50\0\14\11\4\0\20\11\20\0\16\11"+
    "\5\0\2\11\30\0\3\11\40\0\5\11\1\0\207\11\23\0\12\11"+
    "\7\0\32\11\4\0\1\11\1\0\32\11\13\0\131\11\3\0\6\11"+
    "\2\0\6\11\2\0\6\11\2\0\3\11\43\0\14\11\1\0\32\11"+
    "\1\0\23\11\1\0\2\11\1\0\17\11\2\0\16\11\42\0\173\11"+
    "\105\0\65\11\210\0\1\11\202\0\35\11\3\0\61\11\17\0\1\11"+
    "\37\0\40\11\20\0\33\11\5\0\53\11\5\0\36\11\2\0\44\11"+
    "\4\0\10\11\1\0\5\11\52\0\236\11\2\0\12\11\126\0\50\11"+
    "\10\0\64\11\234\0\u0137\11\11\0\26\11\12\0\10\11\230\0\6\11"+
    "\2\0\1\11\1\0\54\11\1\0\2\11\3\0\1\11\2\0\27\11"+
    "\12\0\27\11\11\0\37\11\141\0\26\11\12\0\32\11\106\0\70\11"+
    "\6\0\2\11\100\0\4\11\1\0\2\11\5\0\10\11\1\0\3\11"+
    "\1\0\33\11\4\0\3\11\4\0\1\11\40\0\35\11\3\0\35\11"+
    "\43\0\10\11\1\0\36\11\31\0\66\11\12\0\26\11\12\0\23\11"+
    "\15\0\22\11\156\0\111\11\u03b7\0\107\11\37\0\12\11\17\0\74\11"+
    "\25\0\31\11\7\0\12\11\6\0\65\11\1\0\12\11\20\0\44\11"+
    "\2\0\1\11\11\0\105\11\13\0\13\11\45\0\22\11\1\0\45\11"+
    "\170\0\73\11\5\0\12\11\7\0\3\11\1\0\10\11\2\0\2\11"+
    "\2\0\26\11\1\0\7\11\1\0\2\11\1\0\5\11\2\0\11\11"+
    "\2\0\2\11\2\0\3\11\11\0\1\11\5\0\7\11\2\0\7\11"+
    "\3\0\5\11\u010b\0\106\11\1\0\1\11\10\0\12\11\246\0\66\11"+
    "\2\0\11\11\77\0\101\11\3\0\1\11\13\0\12\11\46\0\70\11"+
    "\10\0\12\11\u01d6\0\112\11\25\0\1\11\u01c0\0\71\11\u0507\0\u0399\11"+
    "\147\0\157\11\u0b91\0\u042f\11\u33d1\0\u0239\11\7\0\37\11\1\0\12\11"+
    "\146\0\36\11\2\0\5\11\13\0\67\11\11\0\4\11\14\0\12\11"+
    "\11\0\25\11\5\0\23\11\u0370\0\105\11\13\0\57\11\20\0\21\11"+
    "\u4060\0\2\11\u0bfe\0\153\11\5\0\15\11\3\0\11\11\7\0\12\11"+
    "\3\0\2\11\u14c6\0\5\11\3\0\6\11\10\0\10\11\2\0\7\11"+
    "\36\0\4\11\224\0\3\11\u01bb\0\125\11\1\0\107\11\1\0\2\11"+
    "\2\0\1\11\2\0\2\11\2\0\4\11\1\0\14\11\1\0\1\11"+
    "\1\0\7\11\1\0\101\11\1\0\4\11\2\0\10\11\1\0\7\11"+
    "\1\0\34\11\1\0\4\11\1\0\5\11\1\0\1\11\3\0\7\11"+
    "\1\0\u0154\11\2\0\31\11\1\0\31\11\1\0\37\11\1\0\31\11"+
    "\1\0\37\11\1\0\31\11\1\0\37\11\1\0\31\11\1\0\37\11"+
    "\1\0\31\11\1\0\10\11\2\0\62\11\u1000\0\305\11\13\0\7\11"+
    "\u0529\0\4\11\1\0\33\11\1\0\2\11\1\0\1\11\2\0\1\11"+
    "\1\0\12\11\1\0\4\11\1\0\1\11\1\0\1\11\6\0\1\11"+
    "\4\0\1\11\1\0\1\11\1\0\1\11\1\0\3\11\1\0\2\11"+
    "\1\0\1\11\2\0\1\11\1\0\1\11\1\0\1\11\1\0\1\11"+
    "\1\0\1\11\1\0\2\11\1\0\1\11\2\0\4\11\1\0\7\11"+
    "\1\0\4\11\1\0\4\11\1\0\1\11\1\0\12\11\1\0\21\11"+
    "\5\0\3\11\1\0\5\11\1\0\21\11\u0274\0\32\11\6\0\32\11"+
    "\6\0\32\11\u0e76\0\ua6d7\11\51\0\u1035\11\13\0\336\11\u3fe2\0\u021e\11"+
    "\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u06ed\0"+
    "\360\11\uffff\0\uffff\0\ufe12\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\1\1\3\1\4\2\5\1\0"+
    "\1\6\1\0\1\7\4\0\1\10\2\0\1\11\1\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[22];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\16\0\34\0\52\0\70\0\106\0\124\0\142"+
    "\0\16\0\52\0\16\0\70\0\16\0\160\0\176\0\214"+
    "\0\232\0\16\0\250\0\266\0\304\0\322";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[22];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\2\1\5\1\2\1\6\1\7"+
    "\1\10\1\2\3\3\1\11\17\0\1\3\10\0\3\3"+
    "\1\0\3\12\1\13\12\12\5\14\1\15\10\14\4\16"+
    "\1\0\15\16\1\0\10\16\1\17\4\16\1\0\2\16"+
    "\1\20\5\16\1\17\11\0\2\21\12\0\2\22\2\21"+
    "\2\0\1\23\4\16\1\0\4\16\2\21\3\16\11\0"+
    "\2\21\1\24\1\25\10\0\2\22\4\0\1\23\11\0"+
    "\2\26\1\24\1\25\1\0\6\25\3\0\5\25\11\0"+
    "\2\26\1\0\1\25\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[224];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\6\1\1\11\1\0\1\11\1\0\1\11"+
    "\4\0\1\11\2\0\1\1\1\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[22];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    /** List of parsed song elements*/
    private static List<SongElement> songElements = new ArrayList<SongElement>();

    /**
     * Returns the parsed song elements
     */
	public static List<SongElement> parse(String file) {
		songElements = new ArrayList<SongElement>();
		LexicalSongParser scanner = null;
		try {
			java.io.FileInputStream stream = new java.io.FileInputStream(file);
			java.io.Reader reader = new java.io.InputStreamReader(stream, "UTF-8");
			scanner = new LexicalSongParser(reader);
			while (!scanner.zzAtEOF)
				scanner.yylex();
		} catch (java.io.FileNotFoundException e) {
			System.out.println("File not found : \"" + file + "\"");
		} catch (java.io.IOException e) {
			System.out.println("IO error scanning file \"" + file + "\"");
			System.out.println(e);
		} catch (Exception e) {
			System.out.println("Unexpected exception:");
			e.printStackTrace();
		}
		return songElements;
	}



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  LexicalSongParser(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2592) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { /*Do nothing*/
            }
          case 10: break;
          case 2: 
            { songElements.add(new WordElement(yyline, yycolumn, yytext()));
            }
          case 11: break;
          case 3: 
            { System.out.print(yytext());
            }
          case 12: break;
          case 4: 
            { songElements.add(new LinebreakElement(yyline, yycolumn, "\n"));
            }
          case 13: break;
          case 5: 
            { songElements.add(new SongElement(SongElementType.WHITESPACE, yyline, yycolumn, " "));
            }
          case 14: break;
          case 6: 
            { songElements.add(new ChordElement(yyline, yycolumn, yytext().replace("[", "").replace("]", "")));
            }
          case 15: break;
          case 7: 
            { songElements.add(new ChordproElement(yyline, yycolumn, yytext().replace("{", "").replace("}", "")));
            }
          case 16: break;
          case 8: 
            { songElements.add(new FakebreakElement(yyline, yycolumn, " "));
            }
          case 17: break;
          case 9: 
            { songElements.add(new OnsongElement(yyline, yycolumn, yytext().trim()));
            }
          case 18: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java LexicalSongParser [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        LexicalSongParser scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new LexicalSongParser(reader);
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
